/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Seven_Segment_Reg.h"
#include "Seven_Segment_aliases.h"
#include "Seven_Segment.h"
#include "Decimal_place_aliases.h"
#include "Decimal_place.h"
#include "Digit_0_aliases.h"
#include "Digit_0.h"
#include "Digit_1_aliases.h"
#include "Digit_1.h"
#include "Digit_2_aliases.h"
#include "Digit_2.h"
#include "Digit_3_aliases.h"
#include "Digit_3.h"
#include "Digit_Reg.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

